sonatypeWork: /sonatype-work/clm-server
clusterDirectory: /sonatype-work/clm-cluster

database:
  type: "postgresql"
  hostname: ${NXIQ_DATABASE_HOSTNAME}
  port: ${NXIQ_DATABASE_PORT}
  name: ${NXIQ_DATABASE_NAME}
  username: ${NXIQ_DATABASE_USERNAME}
  password: ${NXIQ_DATABASE_PASSWORD}

licenseFile: /nxiq-secrets/license.lic

server:
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8070
  adminContextPath: /
  adminConnectors:
    - type: http
      port: 8071
  requestLog:
    appenders:
      # Settings for logging to a file.
      - type: file
        # The file to which current statements will be logged.
        currentLogFilename: /var/log/nexus-iq-server/request.log
        logFormat: '%clientHost %l %user [%date] "%requestURL" %statusCode %bytesSent %elapsedTime "%header{User-Agent}"'
        # When the log file rotates, the archived log will be renamed to this and gzipped. The
        # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
        # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
        archivedLogFilenamePattern: /var/log/nexus-iq-server/request-%d.log.gz
        # The number of archived files to keep.
        archivedFileCount: 5

logging:
  level: INFO
  loggers:
    "com.sonatype.insight.scan": INFO
    "eu.medsea.mimeutil.MimeUtil2": INFO
    "org.apache.http": INFO
    "org.apache.http.wire": ERROR
    "org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader": WARN
    "org.eclipse.jetty": INFO
    "org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter": INFO # WARNING: This reveals credentials at DEBUG level
    "org.quartz": INFO
    "com.networknt.schema": OFF
    "com.sonatype.insight.audit":
      appenders:
        - type: file
          # The file to which audit statements will be logged.
          currentLogFilename: /var/log/nexus-iq-server/audit.log
          # When the audit log file rotates, the archived audit log will be renamed to this and gzipped. The
          # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
          # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
          #
          # If archive is true, this must be specified.
          archivedLogFilenamePattern: /var/log/nexus-iq-server/audit-%d.log.gz
          # The number of archived audit log files to keep.
          archivedFileCount: 5
    "com.sonatype.insight.policy.violation":
      appenders:
        - type: file
          # The file to which policy violations will be logged.
          currentLogFilename: /var/log/nexus-iq-server/policy-violation.log
          # When the policy violation log file rotates, the archived policy violation log will be renamed to this
          # and gzipped. The %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
          # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
          #
          # If archive is true, this must be specified.
          archivedLogFilenamePattern: /var/log/nexus-iq-server/policy-violation-%d.log.gz
          # The number of archived policy violation log files to keep.
          archivedFileCount: 5

  appenders:
    - type: console
      # Do not display log statements below this threshold to stdout.
      threshold: INFO
      logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
    - type: file
      # Do not write log statements below this threshold to the file.
      threshold: ALL
      logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
      # The file to which current statements will be logged.
      currentLogFilename: /var/log/nexus-iq-server/clm-server.log
      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      #
      # If archive is true, this must be specified.
      archivedLogFilenamePattern: /var/log/nexus-iq-server/clm-server-%d.log.gz
      # The number of archived files to keep.
      archivedFileCount: 5