sonatypeWork: /sonatype-work/clm-server
clusterDirectory: /sonatype-work/clm-cluster

database:
  type: "postgresql"
  hostname: ${NXIQ_DATABASE_HOSTNAME}
  port: ${NXIQ_DATABASE_PORT}
  name: ${NXIQ_DATABASE_NAME}
  username: ${NXIQ_DATABASE_USERNAME}
  password: ${NXIQ_DATABASE_PASSWORD}

licenseFile: /nxiq-secrets/license.lic

server:
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8070